<?php
require_once "CommissionEmployee.php";
class BasePlusCommissionEmployee extends CommissionEmployee
{
    //Additional Attribute
    private $baseSalary;

    //Constructor
    public function __construct($firstName, $lastName, $socialSecurityNumber, $grossSales, $commissionRate,$baseSalary)
    {
        parent::__construct($firstName, $lastName, $socialSecurityNumber, $grossSales, $commissionRate);
        $this->baseSalary = $baseSalary;
    }

    //Getter and setter method for baseSalary
    public function getBaseSalary()
    {
        return $this->baseSalary;
}

public function setBaseSalary($baseSalary)
{
    if($baseSalary >= 0.0)
    {
        $this->baseSalary  = $baseSalary;
    }
    else{
        throw new InvalidArgumentException("Base Salary must be greater than or equal to 0.0");
    }
}


//@Override
public function earnings()
{
    return $this->baseSalary +  parent::earnings(); // TODO: Change the autogenerated stub
}

public function display()
{
    echo "Base Salary +Commission Employee :\n";
    echo "Base Salary :" . number_format($this ->baseSalary)  . "\n";
    parent::display(); // TODO: Change the autogenerated stub
}

}